spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      uri: mongodb://localhost:27017/task-db # URI of MongoDB  
  jackson: # Jackson
    default-property-inclusion: NON_NULL # Include only non null properties in output
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8443
  ssl:
    key-store: classpath:keystore/certificate-test.p12
    key-store-password: Qd7b2TzSe7TqMdzh
    key-store-type: pkcs12
    key-alias: kaizten-task-rest-api
    key-password: Qd7b2TzSe7TqMdzh
  error:
    include-message: always

jwt:
  secret: ppwWhEes6RSgaeKY1o7mUNwxqPWzmCvB1gwwaFzbXrlp2XBOmy4u35t0JxZL6Gt5Ki-7bc5-3impk1rtx24yCD2OUPaSbl9LEpLW6qzyOJhcy4Eq3fHGsq-s_qjBgpJYi-mzTcqqC9-UbGjk-Riiq_z1_nJjRMmfC7FrLiOB_1eQIfjY05aoI3CSyGKPVfpi5RCVhlE0jli71PHVPZlDdjy22432Wnsl2uETR7wp6eynzEOfzNQzi23VZIMFlXYep2vsXGRg4iUl5zAhayD5kFRQpnx4G_PwRCxzx4zM5-MDR_3hHveK8-QPi-O33K7hYU1Xu5vDYAVGwpz6p2Rdrw